services:
  postgres_db:
    restart: unless-stopped
    image: postgres:17
    environment:
      POSTGRES_DB: student_info
      POSTGRES_USER: zachary
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  postgres_db:

